from pathlib import Path

root = Path('/home/ubuntu/jimmi-fit-recovery')
ui = root / 'server/onboarding.ui.test.ts'
text = ui.read_text()

replacements = [
    ('const mealPlanSource = readFileSync(join(process.cwd(), "client/src/pages/MealPlan.tsx"), "utf8");\nconst memberMenuSource = readFileSync(join(process.cwd(), "client/src/components/MemberMenu.tsx"), "utf8");',
     'const mealPlanSource = readFileSync(join(process.cwd(), "client/src/pages/MealPlan.tsx"), "utf8");\nconst foodLogSource = readFileSync(join(process.cwd(), "client/src/pages/FoodLog.tsx"), "utf8");\nconst memberMenuSource = readFileSync(join(process.cwd(), "client/src/components/MemberMenu.tsx"), "utf8");'),
    ('expect(onboardingSource).toContain("Name");', 'expect(onboardingSource).toContain("First name");'),
    ('expect(onboardingSource).toContain("Gender");\n    expect(onboardingSource).toContain("SelectInput value={form.gender}");',
     'expect(onboardingSource).toContain("Gender");\n    expect(onboardingSource).toContain("SelectInput value={form.gender}");\n    expect(onboardingSource).toContain(\'const genderOptions = ["Male", "Female"];\');\n    expect(onboardingSource).not.toContain("Non-binary");'),
    ('expect(onboardingSource).toContain("Name is required.");', 'expect(onboardingSource).toContain("First name must be at least 2 characters.");'),
    ('expect(onboardingSource).toContain("Date of birth is required.");\n    expect(onboardingSource).toContain("Gender is required.");',
     'expect(onboardingSource).toContain("Date of birth is required.");\n    expect(onboardingSource).toContain("You must be at least 8 years old to use JIMMI.");\n    expect(onboardingSource).toContain("Select Male or Female.");'),
    ('expect(onboardingSource).toContain("JIMMI stores this securely to keep your profile age current automatically.");',
     'expect(onboardingSource).toContain("JIMMI stores this securely to keep your profile age current automatically. You must be at least 8 years old.");\n    expect(onboardingSource).toContain("placeholder={birthdaySample}");\n    expect(onboardingSource).toContain("max={minimumBirthday}");'),
    ('  it("adds member dropdown navigation with Profile, Macros, Training, Meal Plan, and Logout options", () => {\n    expect(memberMenuSource).toContain("DropdownMenu");\n    expect(memberMenuSource).toContain("View Profile");\n    expect(memberMenuSource).toContain("View Macros");\n    expect(memberMenuSource).toContain("Training Plan");\n    expect(memberMenuSource).toContain("Meal Plan");\n    expect(memberMenuSource).toContain("Logout");\n    expect(memberMenuSource).toContain("trpc.auth.logout.useMutation");\n    expect(chatSource).toContain("<MemberMenu memberName={profile.firstName} isLocalFallback={isLocalFallback} />");\n    expect(profileSource).toContain("<MemberMenu memberName={profile.firstName} isLocalFallback={isLocalFallback} />");\n    expect(profileSource).toContain("Edit Profile");\n    expect(profileSource).not.toContain("Save profile");\n  });',
     '  it("adds avatar-triggered member dropdown navigation with Profile, Macros, Training, Meal Plan, Food Log, and Logout options", () => {\n    expect(memberMenuSource).toContain("DropdownMenu");\n    expect(memberMenuSource).toContain(\'data-member-menu-trigger="avatar"\');\n    expect(memberMenuSource).toContain("Profile avatar");\n    expect(memberMenuSource).toContain("View Profile");\n    expect(memberMenuSource).toContain("View Macros");\n    expect(memberMenuSource).toContain("Training Plan");\n    expect(memberMenuSource).toContain("Meal Plan");\n    expect(memberMenuSource).toContain("Food Log");\n    expect(memberMenuSource).toContain("Logout");\n    expect(memberMenuSource).toContain("trpc.auth.logout.useMutation");\n    expect(chatSource).toContain("<MemberMenu memberName={profile.firstName} avatarUrl={profile.avatarUrl} isLocalFallback={isLocalFallback} />");\n    expect(profileSource).toContain("<MemberMenu memberName={profile.firstName} avatarUrl={profile.avatarUrl} isLocalFallback={isLocalFallback} />");\n    expect(profileSource).toContain("Edit Profile");\n    expect(profileSource).toContain(\'data-profile-photo-capture="true"\');\n    expect(profileSource).toContain(\'capture="user"\');\n    expect(profileSource).toContain("updateAvatar");\n    expect(profileSource).not.toContain("Save profile");\n  });'),
    ('  it("registers dedicated Training Plan and Meal Plan routes that support local fallback profiles", () => {\n    expect(appSource).toContain(\'import TrainingPlan from "@/pages/TrainingPlan";\');\n    expect(appSource).toContain(\'import MealPlan from "@/pages/MealPlan";\');\n    expect(appSource).toContain(\'<Route path="/training-plan" component={TrainingPlan} />\');\n    expect(appSource).toContain(\'<Route path="/meal-plan" component={MealPlan} />\');\n    expect(trainingPlanSource).toContain("buildTrainingPlan(profile)");\n    expect(trainingPlanSource).toContain("redirectOnUnauthenticated: false");\n    expect(trainingPlanSource).toContain("const profile = profileQuery.data ?? localProfile;");\n    expect(mealPlanSource).toContain("buildMacroTargets(profile)");\n    expect(mealPlanSource).toContain("id=\"macros\"");\n    expect(mealPlanSource).toContain("redirectOnUnauthenticated: false");\n    expect(mealPlanSource).toContain("const profile = profileQuery.data ?? localProfile;");\n  });',
     '  it("registers dedicated Training Plan, Meal Plan, and Food Log routes that support local fallback profiles", () => {\n    expect(appSource).toContain(\'import TrainingPlan from "@/pages/TrainingPlan";\');\n    expect(appSource).toContain(\'import MealPlan from "@/pages/MealPlan";\');\n    expect(appSource).toContain(\'import FoodLog from "@/pages/FoodLog";\');\n    expect(appSource).toContain(\'<Route path="/training-plan" component={TrainingPlan} />\');\n    expect(appSource).toContain(\'<Route path="/meal-plan" component={MealPlan} />\');\n    expect(appSource).toContain(\'<Route path="/food-log" component={FoodLog} />\');\n    expect(trainingPlanSource).toContain("buildTrainingPlan(profile)");\n    expect(trainingPlanSource).toContain("redirectOnUnauthenticated: false");\n    expect(trainingPlanSource).toContain("const profile = profileQuery.data ?? localProfile;");\n    expect(mealPlanSource).toContain("buildMacroTargets(profile)");\n    expect(mealPlanSource).toContain("id=\"macros\"");\n    expect(mealPlanSource).toContain("redirectOnUnauthenticated: false");\n    expect(mealPlanSource).toContain("const profile = profileQuery.data ?? localProfile;");\n    expect(foodLogSource).toContain("Log meals with JIMMI");\n    expect(foodLogSource).toContain("redirectOnUnauthenticated: false");\n    expect(foodLogSource).toContain("const profile = profileQuery.data ?? localProfile;");\n  });'),
]
for old, new in replacements:
    if old not in text:
        raise SystemExit(f'Missing UI test pattern: {old[:80]}')
    text = text.replace(old, new, 1)

insert_after = '  it("hides calculated age and section-selector cards from onboarding while preserving birthday collection", () => {\n'
# Add scroll-to-top assertions after the birthday test block if not present.
if 'scrolls each onboarding step transition to the top of the next page' not in text:
    marker = '  });\n\n  it("uses the requested black luxury foundation'
    new_block = '  });\n\n  it("scrolls each onboarding step transition to the top of the next page", () => {\n    expect(onboardingSource).toContain("const previousStepRef = useRef(step);");\n    expect(onboardingSource).toContain("window.requestAnimationFrame(() => {");\n    expect(onboardingSource).toContain(\'window.scrollTo({ top: 0, behavior: "smooth" });\');\n  });\n\n  it("uses the requested black luxury foundation'
    if marker not in text:
        raise SystemExit('Missing insertion marker for scroll-to-top test')
    text = text.replace(marker, new_block, 1)

ui.write_text(text)

backend = root / 'server/jimmi.recovery.test.ts'
b = backend.read_text()
b = b.replace('gender: "Non-binary",', 'gender: "Male",')
b = b.replace('gender: "Non-binary",', 'gender: "Female",')
# The first replace changes all; ensure the rejection test explicitly tests invalid gender through a cast.
b = b.replace('gender: "Male",\n        weight: 180,\n        height: "5 ft 10 in",\n        healthComplications: [],', 'gender: "Non-binary" as any,\n        weight: 180,\n        height: "5 ft 10 in",\n        healthComplications: [],', 1)
if 'updateJimmiProfileAvatar' not in b.split('vi.mock("./db"')[1].split('}));')[0]:
    b = b.replace('  upsertJimmiProfile: vi.fn(async (_userId: number, input: any) => ({\n    ...baseProfile,\n    ...input,\n  })),\n  upsertUser: vi.fn(),', '  upsertJimmiProfile: vi.fn(async (_userId: number, input: any) => ({\n    ...baseProfile,\n    ...input,\n  })),\n  updateJimmiProfileAvatar: vi.fn(async (_userId: number, avatarUrl: string) => ({\n    ...baseProfile,\n    avatarUrl,\n  })),\n  upsertUser: vi.fn(),')
if 'vi.mock("./storage"' not in b:
    b = b.replace('vi.mock("./_core/llm", () => ({\n  invokeLLM: vi.fn(async () => ({\n    choices: [{ message: { content: "Start with two strength sessions and daily walks. Want more detail?" } }],\n  })),\n}));\n', 'vi.mock("./_core/llm", () => ({\n  invokeLLM: vi.fn(async () => ({\n    choices: [{ message: { content: "Start with two strength sessions and daily walks. Want more detail?" } }],\n  })),\n}));\n\nvi.mock("./storage", () => ({\n  storagePut: vi.fn(async () => ({ key: "avatars/user-7/profile.png", url: "/manus-storage/avatars/user-7/profile.png" })),\n}));\n')
b = b.replace('import { getJimmiProfile, upsertJimmiProfile } from "./db";', 'import { getJimmiProfile, upsertJimmiProfile, updateJimmiProfileAvatar } from "./db";')
b = b.replace('import { appRouter } from "./routers";', 'import { storagePut } from "./storage";\nimport { appRouter } from "./routers";')
if 'rejects first names shorter than two characters' not in b:
    insert = '''\n  it("rejects first names shorter than two characters and users younger than 8", async () => {\n    const caller = appRouter.createCaller(createContext({ user: authedUser }));\n\n    await expect(caller.onboarding.complete({\n      firstName: "A",\n      birthday: "2010-01-01",\n      gender: "Male",\n      weight: 180,\n      height: "5 ft 10 in",\n      healthComplications: ["None"],\n      dietRestrictions: ["None"],\n      foodAllergies: ["None"],\n      fitnessLevel: "Intermediate",\n      activityLevel: "Moderate",\n      fitnessGoals: ["Build muscle"],\n      additionalInfo: null,\n    })).rejects.toThrow();\n\n    await expect(caller.onboarding.complete({\n      firstName: "Alex",\n      birthday: new Date().toISOString().slice(0, 10),\n      gender: "Female",\n      weight: 180,\n      height: "5 ft 10 in",\n      healthComplications: ["None"],\n      dietRestrictions: ["None"],\n      foodAllergies: ["None"],\n      fitnessLevel: "Intermediate",\n      activityLevel: "Moderate",\n      fitnessGoals: ["Build muscle"],\n      additionalInfo: null,\n    })).rejects.toThrow();\n  });\n'''
    b = b.replace('  it("saves complete onboarding and returns computed profile metadata", async () => {', insert + '\n  it("saves complete onboarding and returns computed profile metadata", async () => {', 1)
if 'uploads and persists a profile avatar image' not in b:
    insert = '''\n  it("uploads and persists a profile avatar image", async () => {\n    const caller = appRouter.createCaller(createContext({ user: authedUser }));\n    const result = await caller.onboarding.updateAvatar({ imageDataUrl: "data:image/png;base64,aGVsbG8=" });\n\n    expect(storagePut).toHaveBeenCalledWith("avatars/user-7/profile.png", expect.any(Buffer), "image/png");\n    expect(updateJimmiProfileAvatar).toHaveBeenCalledWith(7, "/manus-storage/avatars/user-7/profile.png");\n    expect(result).toMatchObject({ avatarUrl: "/manus-storage/avatars/user-7/profile.png", onboardingComplete: true });\n  });\n'''
    b = b.replace('  it("keeps JIMMI chat restricted to coaching topics before invoking the LLM", async () => {', insert + '\n  it("keeps JIMMI chat restricted to coaching topics before invoking the LLM", async () => {', 1)
backend.write_text(b)
