from pathlib import Path

path = Path('/home/ubuntu/jimmi-fit-recovery/client/src/pages/Home.tsx')
s = path.read_text()

s = s.replace('const nav = [', 'const jimmiLogoUrl = "/manus-storage/jimmi-logo-dark-luxury_6d587e7f.jpeg";\n\nconst nav = [')
s = s.replace('JIMMI Fit', 'JIMMI')
s = s.replace('Recovered JIMMI experience', 'Recovered JIMMI experience')
s = s.replace('bg-[radial-gradient(circle_at_20%_20%,rgba(57,255,20,.22),transparent_28%),radial-gradient(circle_at_80%_10%,rgba(255,46,99,.22),transparent_24%),linear-gradient(135deg,#07070a,#111827_52%,#050507)]', 'bg-[radial-gradient(circle_at_50%_-10%,rgba(255,255,255,.16),transparent_32%),radial-gradient(circle_at_82%_8%,rgba(207,181,112,.14),transparent_26%),linear-gradient(135deg,#000,#050506_50%,#101012)]')
s = s.replace('<Badge className="border-primary/40 bg-primary/10 text-primary">Recovered JIMMI experience</Badge><div className="space-y-4"><h1 className="text-6xl font-black uppercase tracking-[-.08em] sm:text-8xl">JIMMI <span className="text-primary">Fit</span></h1><p className="max-w-2xl text-xl text-muted-foreground">Log workouts, track macros, analyze progress, and ask JIMMI for concise fitness and nutrition coaching powered by your actual history.</p></div>', '<Badge className="border-white/20 bg-white/[.06] text-white">Recovered JIMMI experience</Badge><div className="space-y-5"><img src={jimmiLogoUrl} alt="JIMMI" className="h-24 w-auto rounded-[2rem] border border-white/10 bg-black object-contain p-4 shadow-2xl shadow-black/70 sm:h-32" /><h1 className="jimmi-wordmark text-6xl sm:text-8xl">JIMMI</h1><div className="luxury-divider max-w-xl" /><p className="max-w-2xl text-xl text-muted-foreground">A dark luxury training and nutrition command center for logging workouts, tracking macros, analyzing progress, and receiving history-aware coaching.</p></div>')
s = s.replace('className="font-black uppercase tracking-wide"', 'className="font-black uppercase tracking-[.22em]"')
s = s.replace('Explore Recovery Build', 'Explore Recovery')
s = s.replace('border-primary/40 bg-background/40', 'border-white/20 bg-white/[.04] text-white hover:bg-white/10')
s = s.replace('border-primary/20', 'border-white/15')
s = s.replace('<ScanBarcode className="text-primary" /> Chat-equipped food intelligence', '<ScanBarcode className="text-primary" /> JIMMI food intelligence')
s = s.replace('are being reconstructed into one energetic app shell', 'are reconstructed inside one refined dark luxury command center')
s = s.replace('grid h-11 w-11 place-items-center rounded-2xl bg-primary text-black font-black shadow-[0_0_32px_rgba(57,255,20,.35)]">JF</div><div><div className="text-2xl font-black uppercase tracking-[-.08em]">JIMMI</div><div className="text-[10px] uppercase tracking-[.35em] text-muted-foreground">Recovery Build</div></div>', 'grid h-11 w-11 place-items-center overflow-hidden rounded-2xl border border-white/15 bg-black shadow-[0_18px_45px_rgba(0,0,0,.55)]"><img src={jimmiLogoUrl} alt="JIMMI" className="h-full w-full object-cover" /></div><div><div className="jimmi-wordmark text-2xl">JIMMI</div><div className="text-[10px] uppercase tracking-[.42em] text-muted-foreground">Dark Luxury Fitness</div></div>')
s = s.replace('bg-primary text-black', 'bg-primary text-black')
s = s.replace('hover:border-primary/50 hover:bg-primary hover:text-black', 'hover:border-white/40 hover:bg-white hover:text-black')
s = s.replace('border-primary/40 bg-white/[.05] text-primary shadow-[0_0_28px_rgba(57,255,20,.18)] transition hover:bg-primary hover:text-black', 'border-white/20 bg-white/[.05] text-white shadow-[0_18px_55px_rgba(0,0,0,.45)] transition hover:bg-white hover:text-black')
s = s.replace('bg-[#08090d]/95', 'bg-[#030304]/95')
s = s.replace('<Badge className="bg-primary text-black">BETA</Badge>', '<Badge className="border-white/20 bg-white text-black">JIMMI</Badge>')
s = s.replace('End this JIMMI session', 'End this JIMMI session')
s = s.replace('Daily command center for your training and macros.', 'Your dark luxury command center for training, macros, and momentum.')
s = s.replace('Recover the original fast workout logger with full history.', 'Log training sessions quickly while preserving full workout history.')
s = s.replace('Manual macro logs plus recovered barcode-assisted food lookup.', 'Manual macro logs with barcode-assisted food lookup and premium nutrition context.')
s = s.replace('Barcode recovery lane', 'Barcode scanner')
s = s.replace('Weekly and monthly-style recovery charts', 'Weekly and monthly-style performance charts')
s = s.replace('fill="#39ff14"', 'fill="#f5f1e8"')
s = s.replace('fill="#ff2e63"', 'fill="#c7a96b"')
s = s.replace('stroke="#39ff14"', 'stroke="#f5f1e8"')
s = s.replace('stroke="#ff2e63"', 'stroke="#c7a96b"')
s = s.replace('text-primary', 'text-primary')
s = s.replace('Recovered AI assistant with history-aware coaching, camera/photo input, and food macro analysis.', 'History-aware JIMMI coaching with camera, photo, file, and food macro analysis.')
s = s.replace('Loading profile.', 'Loading JIMMI profile.')
s = s.replace('Targets, timezone, and optional reminder preferences.', 'Targets, timezone, and preference controls for the JIMMI experience.')

path.write_text(s)
print('updated Home.tsx for JIMMI dark luxury branding')
