export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  adminFallbackPassword: process.env.ADMIN_FALLBACK_PASSWORD ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  elevenLabsApiKey: process.env.ELEVENLABS_API_KEY ?? "",
  elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_ID ?? "",
  ouraClientId: process.env.OURA_CLIENT_ID ?? "",
  ouraClientSecret: process.env.OURA_CLIENT_SECRET ?? "",
  whoopClientId: process.env.WHOOP_CLIENT_ID ?? "",
  whoopClientSecret: process.env.WHOOP_CLIENT_SECRET ?? "",
  googleHealthClientId: process.env.GOOGLE_HEALTH_CLIENT_ID ?? "",
  googleHealthClientSecret: process.env.GOOGLE_HEALTH_CLIENT_SECRET ?? "",
  googleHealthRedirectUri: process.env.GOOGLE_HEALTH_REDIRECT_URI ?? "https://askjimmi.com/api/google-health/callback",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripePriceStarterId: process.env.STRIPE_PRICE_STARTER ?? "",
  stripePriceProId: process.env.STRIPE_PRICE_PRO ?? "",
  stripePriceEliteId: process.env.STRIPE_PRICE_ELITE ?? "",
};